services:
  - type: web
    name: eventora-v4
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@eventora.local
      - key: ADMIN_PASSWORD
        sync: false
      - key: PAYTM_ENV
        value: staging
      - key: PAYTM_WEBSITE
        value: WEBSTAGING
      - key: DATABASE_URL
        fromDatabase:
          name: eventora-db
          property: connectionString

databases:
  - name: eventora-db
    plan: free
