services:
  - type: web
    name: eventora
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@eventora.local
      - key: ADMIN_PASSWORD
        value: ChangeThis123!
